import type { Metadata } from "next";
import "./globals.css";
import { londrina, londrinaSolid } from "./fonts";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={londrinaSolid.className}>
        <Navbar />
        <div
          className="bg-cover bg-center w-full h-full"
          style={{ backgroundImage: `url('assets/background.jpg')` }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
